#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 6, y: 0, z: 17}
      rotations: [38]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 6}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 23, y: 0, z: 18}
      rotations: [141]
      sizes: 
      - !Vector3 {x: 3, y: 15, z: 5}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 19, y: 0, z: 23}
      rotations: [80]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 2}
      colors: 
      - !RGB {r: 85, g: 45, b: 114}
