#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 19, y: 0, z: 22}
      rotations: [283]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 14}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 20, y: 0, z: 27}
      rotations: [104]
      sizes: 
      - !Vector3 {x: 3, y: 14, z: 3}
      colors: 
      - !RGB {r: 94, g: 129, b: 66}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 6, y: 0, z: 26}
      rotations: [144]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 8}
