#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 26, y: 0, z: 21}
      rotations: [38]
      sizes: 
      - !Vector3 {x: 10, y: 1, z: 6}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 24, y: 0, z: 30}
      rotations: [309]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 6}
      colors: 
      - !RGB {r: 60, g: 65, b: 170}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 24, y: 0, z: 21}
      rotations: [51]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 8}
      colors: 
      - !RGB {r: 85, g: 118, b: 99}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 20, y: 0, z: 29}
      rotations: [175]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
