#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 20, y: 0, z: 29}
      rotations: [96]
      sizes: 
      - !Vector3 {x: 13, y: 5, z: 7}
      colors: 
      - !RGB {r: 102, g: 223, b: 81}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 18, y: 0, z: 24}
      rotations: [11]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 12, y: 0, z: 21}
      rotations: [318]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 10}
