#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 30, y: 0, z: 19}
      rotations: [327]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 25, y: 0, z: 17}
      rotations: [129]
      sizes: 
      - !Vector3 {x: 2, y: 1, z: 9}
      colors: 
      - !RGB {r: 79, g: 36, b: 140}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 11, y: 0, z: 26}
      rotations: [98]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 8}
      colors: 
      - !RGB {r: 116, g: 2, b: 26}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 15, y: 0, z: 23}
      rotations: [307]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 13}
      colors: 
      - !RGB {r: 254, g: 179, b: 151}
