#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 18, y: 0, z: 28}
      sizes: 
      - !Vector3 {x: 10, y: 10, z: 10}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 17, y: 0, z: 29}
      sizes: 
      - !Vector3 {x: 9, y: 9, z: 9}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 13, y: 0, z: 28}
      sizes: 
      - !Vector3 {x: 7, y: 7, z: 7}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 13, y: 0, z: 17}
      sizes: 
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 16, y: 0, z: 18}
      sizes: 
      - !Vector3 {x: 1, y: 1, z: 1}
