#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 29, y: 0, z: 27}
      rotations: [70]
      sizes: 
      - !Vector3 {x: 8, y: 5, z: 8}
      colors: 
      - !RGB {r: 129, g: 14, b: 246}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 5, y: 0, z: 18}
      rotations: [161]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
      colors: 
      - !RGB {r: 86, g: 171, b: 94}
