#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 35, y: 0, z: 25}
      rotations: [109]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 1}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 33, y: 0, z: 20}
      rotations: [48]
      sizes: 
      - !Vector3 {x: 4, y: 2, z: 5}
      colors: 
      - !RGB {r: 224, g: 90, b: 15}
