#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 17, y: 0, z: 28}
      rotations: [0]
      sizes: 
      - !Vector3 {x: 2, y: 1, z: 9}
      colors: 
      - !RGB {r: 57, g: 209, b: 193}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 29, y: 0, z: 23}
      rotations: [94]
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 10}
      colors: 
      - !RGB {r: 144, g: 14, b: 167}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 7, y: 0, z: 29}
      rotations: [334]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 2}
      colors: 
      - !RGB {r: 34, g: 207, b: 160}
