#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 34, y: 0, z: 20}
      rotations: [99]
      sizes: 
      - !Vector3 {x: 6, y: 4, z: 6}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 14, y: 0, z: 28}
      rotations: [16]
      sizes: 
      - !Vector3 {x: 2, y: 9, z: 3}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 6, y: 0, z: 22}
      rotations: [315]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 8}
      colors: 
      - !RGB {r: 64, g: 209, b: 37}
