#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 32, y: 0, z: 17}
      rotations: [21]
      sizes: 
      - !Vector3 {x: 5, y: 10, z: 1}
      colors: 
      - !RGB {r: 205, g: 93, b: 11}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 27, y: 0, z: 30}
      rotations: [279]
      sizes: 
      - !Vector3 {x: 4, y: 4, z: 7}
      colors: 
      - !RGB {r: 10, g: 118, b: 10}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 7, y: 0, z: 20}
      rotations: [330]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 6}
      colors: 
      - !RGB {r: 138, g: 106, b: 100}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 6, y: 0, z: 19}
      rotations: [209]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 14}
