#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 17, y: 0, z: 19}
      rotations: [230]
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 10}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 24, y: 0, z: 24}
      rotations: [209]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
      colors: 
      - !RGB {r: 205, g: 237, b: 83}
