#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 22, y: 0, z: 26}
      rotations: [241]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
      colors: 
      - !RGB {r: 66, g: 133, b: 238}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 21, y: 0, z: 21}
      rotations: [6]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
      colors: 
      - !RGB {r: 76, g: 227, b: 76}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 23, y: 0, z: 30}
      rotations: [276]
      sizes: 
      - !Vector3 {x: 2, y: 9, z: 3}
      colors: 
      - !RGB {r: 207, g: 230, b: 195}
