#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 35, y: 0, z: 24}
      rotations: [291]
      sizes: 
      - !Vector3 {x: 2, y: 12, z: 2}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 17, y: 0, z: 22}
      rotations: [134]
      sizes: 
      - !Vector3 {x: 2, y: 12, z: 2}
      colors: 
      - !RGB {r: 69, g: 233, b: 173}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 31, y: 0, z: 17}
      rotations: [225]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 96, g: 216, b: 229}
