#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 7, y: 0, z: 30}
      rotations: [224]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
      colors: 
      - !RGB {r: 250, g: 228, b: 31}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 24, y: 0, z: 21}
      rotations: [219]
      sizes: 
      - !Vector3 {x: 5, y: 8, z: 3}
      colors: 
      - !RGB {r: 151, g: 209, b: 164}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 26, y: 0, z: 21}
      rotations: [302]
      sizes: 
      - !Vector3 {x: 2, y: 13, z: 5}
      colors: 
      - !RGB {r: 214, g: 209, b: 29}
