#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 24, y: 0, z: 18}
      rotations: [214]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 5}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 33, y: 0, z: 18}
      rotations: [183]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 2}
      colors: 
      - !RGB {r: 112, g: 106, b: 133}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 27, y: 0, z: 29}
      rotations: [232]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
      colors: 
      - !RGB {r: 66, g: 152, b: 87}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 27, y: 0, z: 25}
      rotations: [23]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
