#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 25, y: 0, z: 24}
      rotations: [7]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 14}
      colors: 
      - !RGB {r: 62, g: 248, b: 29}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 9, y: 0, z: 27}
      rotations: [141]
      sizes: 
      - !Vector3 {x: 3, y: 14, z: 3}
      colors: 
      - !RGB {r: 138, g: 114, b: 58}
