#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 23, y: 0, z: 30}
      rotations: [49]
      sizes: 
      - !Vector3 {x: 2, y: 12, z: 2}
      colors: 
      - !RGB {r: 85, g: 67, b: 113}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 14, y: 0, z: 29}
      rotations: [298]
      sizes: 
      - !Vector3 {x: 3, y: 15, z: 5}
      colors: 
      - !RGB {r: 43, g: 157, b: 78}
