#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 5, y: 0, z: 23}
      rotations: [25]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 10}
      colors: 
      - !RGB {r: 58, g: 32, b: 8}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 16, y: 0, z: 22}
      rotations: [346]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 29, y: 0, z: 29}
      rotations: [96]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 14}
      colors: 
      - !RGB {r: 46, g: 44, b: 171}
