#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 18, y: 0, z: 30}
      rotations: [81]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
      colors: 
      - !RGB {r: 159, g: 103, b: 207}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 10, y: 0, z: 23}
      rotations: [212]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 15}
