#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 27, y: 0, z: 28}
      rotations: [62]
      sizes: 
      - !Vector3 {x: 8, y: 1, z: 11}
      colors: 
      - !RGB {r: 251, g: 189, b: 3}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 16, y: 0, z: 17}
      rotations: [225]
      sizes: 
      - !Vector3 {x: 1, y: 2, z: 8}
      colors: 
      - !RGB {r: 191, g: 23, b: 36}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 12, y: 0, z: 24}
      rotations: [39]
      sizes: 
      - !Vector3 {x: 10, y: 1, z: 6}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 5, y: 0, z: 27}
      rotations: [125]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
      colors: 
      - !RGB {r: 79, g: 253, b: 94}
