#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 15, y: 0, z: 25}
      rotations: [91]
      sizes: 
      - !Vector3 {x: 6, y: 4, z: 6}
      colors: 
      - !RGB {r: 205, g: 136, b: 135}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 34, y: 0, z: 20}
      rotations: [132]
      sizes: 
      - !Vector3 {x: 6, y: 4, z: 6}
      colors: 
      - !RGB {r: 177, g: 168, b: 187}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 12, y: 0, z: 25}
      rotations: [202]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
      colors: 
      - !RGB {r: 59, g: 97, b: 41}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 32, y: 0, z: 20}
      rotations: [297]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 25, y: 0, z: 29}
      rotations: [285]
      sizes: 
      - !Vector3 {x: 6, y: 4, z: 6}
