#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 25, y: 0, z: 21}
      rotations: [283]
      sizes: 
      - !Vector3 {x: 8, y: 5, z: 8}
      colors: 
      - !RGB {r: 5, g: 234, b: 203}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 5, y: 0, z: 18}
      rotations: [231]
      sizes: 
      - !Vector3 {x: 1, y: 2, z: 8}
      colors: 
      - !RGB {r: 175, g: 1, b: 84}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 35, y: 0, z: 20}
      rotations: [249]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 8}
      colors: 
      - !RGB {r: 0, g: 96, b: 35}
