#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 13, y: 0, z: 21}
      sizes: 
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 14, y: 0, z: 19}
      sizes: 
      - !Vector3 {x: 9, y: 9, z: 9}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 27, y: 0, z: 20}
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 5}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 32, y: 0, z: 28}
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 5}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 16, y: 0, z: 28}
      sizes: 
      - !Vector3 {x: 6, y: 6, z: 6}
