#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 8, y: 0, z: 23}
      rotations: [336]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 6, y: 0, z: 17}
      rotations: [317]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
      colors: 
      - !RGB {r: 36, g: 178, b: 97}
