#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 11, y: 0, z: 25}
      rotations: [276]
      sizes: 
      - !Vector3 {x: 7, y: 5, z: 9}
      colors: 
      - !RGB {r: 208, g: 7, b: 31}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 32, y: 0, z: 21}
      rotations: [103]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 14}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 35, y: 0, z: 29}
      rotations: [71]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
      colors: 
      - !RGB {r: 175, g: 163, b: 116}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 17, y: 0, z: 21}
      rotations: [292]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
      colors: 
      - !RGB {r: 20, g: 99, b: 219}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 11, y: 0, z: 20}
      rotations: [3]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
