#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 8, y: 0, z: 17}
      rotations: [312]
      sizes: 
      - !Vector3 {x: 4, y: 3, z: 7}
      colors: 
      - !RGB {r: 212, g: 227, b: 184}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 7, y: 0, z: 29}
      rotations: [23]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 2}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 33, y: 0, z: 24}
      rotations: [74]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 33, y: 0, z: 27}
      rotations: [143]
      sizes: 
      - !Vector3 {x: 2, y: 8, z: 2}
      colors: 
      - !RGB {r: 207, g: 204, b: 16}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 20, y: 0, z: 25}
      rotations: [15]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
