#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 24, y: 0, z: 29}
      rotations: [29]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 15}
      colors: 
      - !RGB {r: 218, g: 168, b: 78}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 20, y: 0, z: 25}
      rotations: [36]
      sizes: 
      - !Vector3 {x: 5, y: 13, z: 3}
      colors: 
      - !RGB {r: 167, g: 215, b: 12}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 24, y: 0, z: 29}
      rotations: [225]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
