#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 35, y: 0, z: 19}
      rotations: [198]
      sizes: 
      - !Vector3 {x: 13, y: 5, z: 7}
      colors: 
      - !RGB {r: 97, g: 70, b: 177}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 12, y: 0, z: 19}
      rotations: [331]
      sizes: 
      - !Vector3 {x: 2, y: 13, z: 5}
      colors: 
      - !RGB {r: 248, g: 73, b: 19}
