#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 32, y: 0, z: 29}
      rotations: [16]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
      colors: 
      - !RGB {r: 133, g: 102, b: 152}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 8, y: 0, z: 28}
      rotations: [20]
      sizes: 
      - !Vector3 {x: 4, y: 2, z: 5}
      colors: 
      - !RGB {r: 192, g: 5, b: 182}
