#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 15, y: 0, z: 29}
      rotations: [332]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 14}
      colors: 
      - !RGB {r: 157, g: 69, b: 47}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 35, y: 0, z: 18}
      rotations: [339]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
      colors: 
      - !RGB {r: 71, g: 43, b: 5}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 30, y: 0, z: 18}
      rotations: [203]
      sizes: 
      - !Vector3 {x: 7, y: 5, z: 9}
