#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 34, y: 0, z: 21}
      rotations: [60]
      sizes: 
      - !Vector3 {x: 10, y: 1, z: 6}
      colors: 
      - !RGB {r: 250, g: 114, b: 13}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 27, y: 0, z: 25}
      rotations: [167]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 14}
      colors: 
      - !RGB {r: 34, g: 36, b: 96}
