#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 32, y: 0, z: 29}
      rotations: [173]
      sizes: 
      - !Vector3 {x: 3, y: 15, z: 5}
      colors: 
      - !RGB {r: 231, g: 51, b: 209}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 12, y: 0, z: 20}
      rotations: [275]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 15}
      colors: 
      - !RGB {r: 160, g: 216, b: 54}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 24, y: 0, z: 30}
      rotations: [259]
      sizes: 
      - !Vector3 {x: 4, y: 6, z: 5}
      colors: 
      - !RGB {r: 20, g: 48, b: 145}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 35, y: 0, z: 19}
      rotations: [186]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 5}
      colors: 
      - !RGB {r: 80, g: 211, b: 23}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 6, y: 0, z: 20}
      rotations: [96]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 5}
      colors: 
      - !RGB {r: 26, g: 31, b: 74}
