#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 6, y: 0, z: 20}
      rotations: [254]
      sizes: 
      - !Vector3 {x: 2, y: 9, z: 3}
      colors: 
      - !RGB {r: 136, g: 109, b: 168}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 17, y: 0, z: 19}
      rotations: [84]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 8}
      colors: 
      - !RGB {r: 8, g: 80, b: 142}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 22, y: 0, z: 20}
      rotations: [350]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 6}
      colors: 
      - !RGB {r: 241, g: 97, b: 233}
