#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 20, y: 0, z: 28}
      rotations: [175]
      sizes: 
      - !Vector3 {x: 2, y: 8, z: 2}
      colors: 
      - !RGB {r: 142, g: 28, b: 28}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 32, y: 0, z: 30}
      rotations: [259]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
      colors: 
      - !RGB {r: 176, g: 163, b: 162}
