#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 9, y: 0, z: 17}
      rotations: [294]
      sizes: 
      - !Vector3 {x: 2, y: 9, z: 3}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 22, y: 0, z: 21}
      rotations: [149]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
      colors: 
      - !RGB {r: 241, g: 209, b: 138}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 34, y: 0, z: 19}
      rotations: [50]
      sizes: 
      - !Vector3 {x: 4, y: 4, z: 7}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 35, y: 0, z: 21}
      rotations: [139]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
      colors: 
      - !RGB {r: 148, g: 48, b: 62}
