#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 13, y: 0, z: 22}
      rotations: [350]
      sizes: 
      - !Vector3 {x: 5, y: 10, z: 1}
      colors: 
      - !RGB {r: 22, g: 232, b: 205}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 18, y: 0, z: 27}
      rotations: [223]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 1}
      colors: 
      - !RGB {r: 129, g: 217, b: 144}
