#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 12, y: 0, z: 21}
      rotations: [346]
      sizes: 
      - !Vector3 {x: 5, y: 8, z: 3}
      colors: 
      - !RGB {r: 189, g: 138, b: 147}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 24, y: 0, z: 21}
      rotations: [77]
      sizes: 
      - !Vector3 {x: 3, y: 4, z: 8}
      colors: 
      - !RGB {r: 123, g: 17, b: 194}
