#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 32, y: 0, z: 25}
      rotations: [303]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 10}
      colors: 
      - !RGB {r: 148, g: 172, b: 20}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 9, y: 0, z: 23}
      rotations: [137]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 13}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 19, y: 0, z: 18}
      rotations: [10]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 5}
      colors: 
      - !RGB {r: 96, g: 136, b: 32}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 29, y: 0, z: 26}
      rotations: [284]
      sizes: 
      - !Vector3 {x: 4, y: 6, z: 5}
      colors: 
      - !RGB {r: 123, g: 92, b: 110}
