#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 21, y: 0, z: 21}
      rotations: [335]
      sizes: 
      - !Vector3 {x: 2, y: 4, z: 14}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 6, y: 0, z: 27}
      rotations: [62]
      sizes: 
      - !Vector3 {x: 2, y: 1, z: 9}
      colors: 
      - !RGB {r: 101, g: 89, b: 241}
