#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 25, y: 0, z: 19}
      rotations: [2]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 10}
      colors: 
      - !RGB {r: 75, g: 13, b: 229}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 9, y: 0, z: 23}
      rotations: [79]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 70, g: 131, b: 127}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 29, y: 0, z: 22}
      rotations: [57]
      sizes: 
      - !Vector3 {x: 2, y: 1, z: 9}
      colors: 
      - !RGB {r: 56, g: 74, b: 65}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 28, y: 0, z: 27}
      rotations: [113]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
      colors: 
      - !RGB {r: 68, g: 250, b: 234}
