#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 10, y: 0, z: 29}
      rotations: [152]
      sizes: 
      - !Vector3 {x: 6, y: 4, z: 6}
      colors: 
      - !RGB {r: 20, g: 238, b: 37}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 33, y: 0, z: 21}
      rotations: [224]
      sizes: 
      - !Vector3 {x: 9, y: 4, z: 8}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 35, y: 0, z: 21}
      rotations: [343]
      sizes: 
      - !Vector3 {x: 2, y: 12, z: 2}
      colors: 
      - !RGB {r: 7, g: 139, b: 176}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 10, y: 0, z: 28}
      rotations: [9]
      sizes: 
      - !Vector3 {x: 2, y: 12, z: 2}
      colors: 
      - !RGB {r: 93, g: 236, b: 92}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 9, y: 0, z: 27}
      rotations: [163]
      sizes: 
      - !Vector3 {x: 3, y: 14, z: 3}
      colors: 
      - !RGB {r: 137, g: 55, b: 199}
