#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 5, y: 0, z: 22}
      rotations: [237]
      sizes: 
      - !Vector3 {x: 5, y: 13, z: 3}
      colors: 
      - !RGB {r: 140, g: 45, b: 190}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 6, y: 0, z: 29}
      rotations: [54]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 14}
      colors: 
      - !RGB {r: 79, g: 28, b: 244}
