#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 31, y: 0, z: 21}
      rotations: [169]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 14}
      colors: 
      - !RGB {r: 90, g: 178, b: 16}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 32, y: 0, z: 30}
      rotations: [308]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
      colors: 
      - !RGB {r: 20, g: 177, b: 60}
