#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 30, y: 0, z: 29}
      rotations: [60]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
      colors: 
      - !RGB {r: 66, g: 184, b: 55}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 18, y: 0, z: 23}
      rotations: [317]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 1}
