#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 14, y: 0, z: 19}
      rotations: [347]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
      colors: 
      - !RGB {r: 5, g: 23, b: 59}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 33, y: 0, z: 29}
      rotations: [202]
      sizes: 
      - !Vector3 {x: 2, y: 13, z: 5}
      colors: 
      - !RGB {r: 93, g: 176, b: 30}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 31, y: 0, z: 21}
      rotations: [330]
      sizes: 
      - !Vector3 {x: 2, y: 1, z: 9}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 8, y: 0, z: 20}
      rotations: [9]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
      colors: 
      - !RGB {r: 140, g: 136, b: 184}
