#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 18, y: 0, z: 17}
      rotations: [260]
      sizes: 
      - !Vector3 {x: 2, y: 4, z: 14}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 35, y: 0, z: 18}
      rotations: [44]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 14}
      colors: 
      - !RGB {r: 39, g: 33, b: 155}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 10, y: 0, z: 28}
      rotations: [69]
      sizes: 
      - !Vector3 {x: 4, y: 6, z: 5}
      colors: 
      - !RGB {r: 114, g: 166, b: 52}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 33, y: 0, z: 17}
      rotations: [265]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
      colors: 
      - !RGB {r: 217, g: 45, b: 44}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 27, y: 0, z: 27}
      rotations: [350]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 1}
