#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 33, y: 0, z: 21}
      sizes: 
      - !Vector3 {x: 7, y: 7, z: 7}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 8, y: 0, z: 24}
      sizes: 
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 9, y: 0, z: 21}
      sizes: 
      - !Vector3 {x: 8, y: 8, z: 8}
