#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 23, y: 0, z: 30}
      rotations: [334]
      sizes: 
      - !Vector3 {x: 2, y: 9, z: 3}
      colors: 
      - !RGB {r: 57, g: 122, b: 52}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 18, y: 0, z: 29}
      rotations: [129]
      sizes: 
      - !Vector3 {x: 3, y: 15, z: 5}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 16, y: 0, z: 30}
      rotations: [73]
      sizes: 
      - !Vector3 {x: 4, y: 4, z: 7}
      colors: 
      - !RGB {r: 212, g: 152, b: 235}
