#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 14, y: 0, z: 23}
      rotations: [298]
      sizes: 
      - !Vector3 {x: 10, y: 5, z: 5}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 10, y: 0, z: 24}
      rotations: [331]
      sizes: 
      - !Vector3 {x: 1, y: 12, z: 3}
      colors: 
      - !RGB {r: 103, g: 173, b: 164}
