#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 15, y: 0, z: 21}
      rotations: [24]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 25, y: 0, z: 18}
      rotations: [96]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 13}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 25, y: 0, z: 23}
      rotations: [108]
      sizes: 
      - !Vector3 {x: 5, y: 11, z: 4}
      colors: 
      - !RGB {r: 153, g: 60, b: 49}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 17, y: 0, z: 26}
      rotations: [68]
      sizes: 
      - !Vector3 {x: 5, y: 8, z: 3}
      colors: 
      - !RGB {r: 47, g: 146, b: 63}
