#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 23, y: 0, z: 18}
      rotations: [55]
      sizes: 
      - !Vector3 {x: 4, y: 3, z: 7}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 10, y: 0, z: 30}
      rotations: [281]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
      colors: 
      - !RGB {r: 136, g: 183, b: 2}
