#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 23, y: 0, z: 18}
      rotations: [270]
      sizes: 
      - !Vector3 {x: 3, y: 4, z: 8}
      colors: 
      - !RGB {r: 184, g: 9, b: 32}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 34, y: 0, z: 18}
      rotations: [241]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 13}
      colors: 
      - !RGB {r: 24, g: 38, b: 253}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 16, y: 0, z: 21}
      rotations: [55]
      sizes: 
      - !Vector3 {x: 1, y: 12, z: 3}
      colors: 
      - !RGB {r: 94, g: 214, b: 130}
