#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 34, y: 0, z: 17}
      rotations: [223]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 11}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 30, y: 0, z: 25}
      rotations: [191]
      sizes: 
      - !Vector3 {x: 5, y: 13, z: 3}
      colors: 
      - !RGB {r: 223, g: 171, b: 38}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 9, y: 0, z: 25}
      rotations: [272]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
      colors: 
      - !RGB {r: 247, g: 237, b: 216}
