#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 12, y: 0, z: 20}
      rotations: [7]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 141, g: 196, b: 203}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 35, y: 0, z: 24}
      rotations: [307]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 6}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 32, y: 0, z: 25}
      rotations: [157]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 10}
      colors: 
      - !RGB {r: 83, g: 62, b: 237}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 35, y: 0, z: 21}
      rotations: [31]
      sizes: 
      - !Vector3 {x: 9, y: 4, z: 8}
