#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 8, y: 0, z: 24}
      rotations: [324]
      sizes: 
      - !Vector3 {x: 5, y: 10, z: 1}
      colors: 
      - !RGB {r: 67, g: 129, b: 12}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 9, y: 0, z: 22}
      rotations: [12]
      sizes: 
      - !Vector3 {x: 5, y: 8, z: 3}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 34, y: 0, z: 27}
      rotations: [58]
      sizes: 
      - !Vector3 {x: 2, y: 8, z: 2}
      colors: 
      - !RGB {r: 119, g: 94, b: 109}
