#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 30, y: 0, z: 22}
      rotations: [139]
      sizes: 
      - !Vector3 {x: 2, y: 12, z: 2}
      colors: 
      - !RGB {r: 98, g: 69, b: 42}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 12, y: 0, z: 20}
      rotations: [169]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 8}
      colors: 
      - !RGB {r: 64, g: 139, b: 65}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 7, y: 0, z: 21}
      rotations: [286]
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 10}
      colors: 
      - !RGB {r: 231, g: 202, b: 175}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 6, y: 0, z: 27}
      rotations: [136]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 14}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 13, y: 0, z: 20}
      rotations: [328]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 11}
      colors: 
      - !RGB {r: 6, g: 47, b: 176}
