#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 24, y: 0, z: 24}
      rotations: [36]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
      colors: 
      - !RGB {r: 83, g: 194, b: 108}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 19, y: 0, z: 26}
      rotations: [127]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 14}
      colors: 
      - !RGB {r: 27, g: 187, b: 67}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 31, y: 0, z: 21}
      rotations: [132]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 14}
      colors: 
      - !RGB {r: 117, g: 135, b: 149}
