#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 5, y: 0, z: 28}
      rotations: [271]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 7, g: 21, b: 207}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 32, y: 0, z: 30}
      rotations: [328]
      sizes: 
      - !Vector3 {x: 2, y: 4, z: 14}
      colors: 
      - !RGB {r: 194, g: 226, b: 128}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 34, y: 0, z: 20}
      rotations: [182]
      sizes: 
      - !Vector3 {x: 8, y: 5, z: 8}
      colors: 
      - !RGB {r: 226, g: 77, b: 118}
