#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 24, y: 0, z: 18}
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 3}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 22, y: 0, z: 22}
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 3}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 15, y: 0, z: 17}
      sizes: 
      - !Vector3 {x: 6, y: 6, z: 6}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 13, y: 0, z: 28}
      sizes: 
      - !Vector3 {x: 7, y: 7, z: 7}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 5, y: 0, z: 19}
      sizes: 
      - !Vector3 {x: 9, y: 9, z: 9}
