#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 21, y: 0, z: 17}
      rotations: [317]
      sizes: 
      - !Vector3 {x: 7, y: 5, z: 9}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 12, y: 0, z: 30}
      rotations: [258]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 21, y: 0, z: 27}
      rotations: [167]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 10}
      colors: 
      - !RGB {r: 245, g: 29, b: 234}
