#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 15, y: 0, z: 17}
      rotations: [62]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
      colors: 
      - !RGB {r: 54, g: 219, b: 66}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 24, y: 0, z: 28}
      rotations: [156]
      sizes: 
      - !Vector3 {x: 5, y: 13, z: 3}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 18, y: 0, z: 25}
      rotations: [242]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
      colors: 
      - !RGB {r: 51, g: 89, b: 13}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 16, y: 0, z: 19}
      rotations: [255]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
      colors: 
      - !RGB {r: 185, g: 156, b: 239}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 32, y: 0, z: 25}
      rotations: [251]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 6}
