#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 17, y: 0, z: 21}
      rotations: [203]
      sizes: 
      - !Vector3 {x: 1, y: 12, z: 3}
      colors: 
      - !RGB {r: 55, g: 205, b: 126}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 9, y: 0, z: 17}
      rotations: [298]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
      colors: 
      - !RGB {r: 239, g: 217, b: 199}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 7, y: 0, z: 17}
      rotations: [144]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
      colors: 
      - !RGB {r: 96, g: 79, b: 188}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 31, y: 0, z: 23}
      rotations: [276]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 8, y: 0, z: 26}
      rotations: [188]
      sizes: 
      - !Vector3 {x: 3, y: 15, z: 5}
      colors: 
      - !RGB {r: 2, g: 76, b: 157}
