#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 35, y: 0, z: 23}
      rotations: [224]
      sizes: 
      - !Vector3 {x: 3, y: 14, z: 3}
      colors: 
      - !RGB {r: 167, g: 175, b: 21}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 22, y: 0, z: 23}
      rotations: [265]
      sizes: 
      - !Vector3 {x: 2, y: 1, z: 9}
