#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 7, y: 0, z: 26}
      rotations: [228]
      sizes: 
      - !Vector3 {x: 2, y: 13, z: 5}
      colors: 
      - !RGB {r: 99, g: 221, b: 204}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 28, y: 0, z: 23}
      rotations: [269]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 5}
      colors: 
      - !RGB {r: 67, g: 89, b: 18}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 23, y: 0, z: 29}
      rotations: [184]
      sizes: 
      - !Vector3 {x: 1, y: 2, z: 8}
      colors: 
      - !RGB {r: 90, g: 216, b: 45}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 13, y: 0, z: 22}
      rotations: [93]
      sizes: 
      - !Vector3 {x: 7, y: 5, z: 9}
      colors: 
      - !RGB {r: 146, g: 161, b: 48}
