#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 33, y: 0, z: 24}
      rotations: [187]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 11}
      colors: 
      - !RGB {r: 157, g: 111, b: 112}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 32, y: 0, z: 25}
      rotations: [321]
      sizes: 
      - !Vector3 {x: 5, y: 13, z: 3}
      colors: 
      - !RGB {r: 238, g: 250, b: 64}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 19, y: 0, z: 19}
      rotations: [297]
      sizes: 
      - !Vector3 {x: 2, y: 9, z: 3}
      colors: 
      - !RGB {r: 202, g: 122, b: 137}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 32, y: 0, z: 29}
      rotations: [49]
      sizes: 
      - !Vector3 {x: 13, y: 5, z: 7}
      colors: 
      - !RGB {r: 57, g: 0, b: 108}
