#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 14, y: 0, z: 18}
      rotations: [199]
      sizes: 
      - !Vector3 {x: 2, y: 4, z: 14}
      colors: 
      - !RGB {r: 160, g: 82, b: 92}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 35, y: 0, z: 30}
      rotations: [120]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 16, y: 0, z: 19}
      rotations: [301]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 11}
      colors: 
      - !RGB {r: 138, g: 47, b: 243}
