#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 30, y: 0, z: 29}
      rotations: [78]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
      colors: 
      - !RGB {r: 65, g: 233, b: 19}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 18, y: 0, z: 24}
      rotations: [301]
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 10}
