#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 32, y: 0, z: 20}
      rotations: [278]
      sizes: 
      - !Vector3 {x: 10, y: 5, z: 5}
      colors: 
      - !RGB {r: 64, g: 27, b: 89}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 21, y: 0, z: 19}
      rotations: [11]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 8}
      colors: 
      - !RGB {r: 173, g: 137, b: 249}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 32, y: 0, z: 22}
      rotations: [43]
      sizes: 
      - !Vector3 {x: 2, y: 8, z: 2}
      colors: 
      - !RGB {r: 241, g: 238, b: 137}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 27, y: 0, z: 26}
      rotations: [165]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
