#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 16, y: 0, z: 18}
      sizes: 
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 21, y: 0, z: 23}
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 3}
