#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 35, y: 0, z: 27}
      rotations: [336]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
      colors: 
      - !RGB {r: 25, g: 240, b: 143}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 20, y: 0, z: 22}
      rotations: [243]
      sizes: 
      - !Vector3 {x: 4, y: 2, z: 5}
      colors: 
      - !RGB {r: 72, g: 94, b: 220}
