#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 29, y: 0, z: 24}
      rotations: [42]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
      colors: 
      - !RGB {r: 255, g: 89, b: 215}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 7, y: 0, z: 17}
      rotations: [129]
      sizes: 
      - !Vector3 {x: 5, y: 8, z: 3}
      colors: 
      - !RGB {r: 200, g: 240, b: 157}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 21, y: 0, z: 21}
      rotations: [26]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
