#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 9, y: 0, z: 17}
      rotations: [318]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 14}
      colors: 
      - !RGB {r: 242, g: 72, b: 70}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 16, y: 0, z: 26}
      rotations: [217]
      sizes: 
      - !Vector3 {x: 1, y: 15, z: 5}
      colors: 
      - !RGB {r: 9, g: 58, b: 80}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 31, y: 0, z: 23}
      rotations: [256]
      sizes: 
      - !Vector3 {x: 13, y: 5, z: 7}
      colors: 
      - !RGB {r: 99, g: 176, b: 245}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 29, y: 0, z: 23}
      rotations: [268]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 6}
      colors: 
      - !RGB {r: 123, g: 103, b: 70}
