#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 31, y: 0, z: 27}
      rotations: [258]
      sizes: 
      - !Vector3 {x: 1, y: 15, z: 5}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 34, y: 0, z: 17}
      rotations: [300]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 14}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 21, y: 0, z: 21}
      rotations: [165]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
      colors: 
      - !RGB {r: 62, g: 218, b: 210}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 23, y: 0, z: 26}
      rotations: [160]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 8}
      colors: 
      - !RGB {r: 200, g: 128, b: 95}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 16, y: 0, z: 19}
      rotations: [131]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 8}
      colors: 
      - !RGB {r: 84, g: 168, b: 238}
