#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 33, y: 0, z: 30}
      rotations: [249]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
      colors: 
      - !RGB {r: 208, g: 24, b: 72}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 28, y: 0, z: 19}
      rotations: [202]
      sizes: 
      - !Vector3 {x: 1, y: 15, z: 5}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 31, y: 0, z: 25}
      rotations: [7]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 47, g: 251, b: 124}
