#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 28, y: 0, z: 25}
      rotations: [107]
      sizes: 
      - !Vector3 {x: 9, y: 4, z: 8}
      colors: 
      - !RGB {r: 151, g: 209, b: 140}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 6, y: 0, z: 28}
      rotations: [294]
      sizes: 
      - !Vector3 {x: 1, y: 15, z: 5}
      colors: 
      - !RGB {r: 221, g: 81, b: 252}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 9, y: 0, z: 27}
      rotations: [326]
      sizes: 
      - !Vector3 {x: 2, y: 1, z: 9}
      colors: 
      - !RGB {r: 233, g: 90, b: 197}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 6, y: 0, z: 26}
      rotations: [199]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 8}
      colors: 
      - !RGB {r: 59, g: 189, b: 92}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 8, y: 0, z: 29}
      rotations: [81]
      sizes: 
      - !Vector3 {x: 9, y: 4, z: 8}
      colors: 
      - !RGB {r: 86, g: 10, b: 157}
