#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 27, y: 0, z: 27}
      rotations: [191]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 1}
      colors: 
      - !RGB {r: 189, g: 222, b: 210}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 33, y: 0, z: 21}
      rotations: [21]
      sizes: 
      - !Vector3 {x: 13, y: 5, z: 7}
      colors: 
      - !RGB {r: 12, g: 10, b: 161}
