#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 14, y: 0, z: 24}
      rotations: [95]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 6}
      colors: 
      - !RGB {r: 31, g: 147, b: 194}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 35, y: 0, z: 21}
      rotations: [153]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 14}
      colors: 
      - !RGB {r: 189, g: 128, b: 124}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 29, y: 0, z: 17}
      rotations: [312]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 14}
      colors: 
      - !RGB {r: 14, g: 138, b: 114}
