#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 29, y: 0, z: 25}
      rotations: [3]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
      colors: 
      - !RGB {r: 60, g: 118, b: 17}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 14, y: 0, z: 17}
      rotations: [40]
      sizes: 
      - !Vector3 {x: 2, y: 8, z: 2}
      colors: 
      - !RGB {r: 98, g: 62, b: 233}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 10, y: 0, z: 21}
      rotations: [251]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 13}
