#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 17, y: 0, z: 23}
      sizes: 
      - !Vector3 {x: 4, y: 4, z: 4}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 23, y: 0, z: 24}
      sizes: 
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 9, y: 0, z: 18}
      sizes: 
      - !Vector3 {x: 4, y: 4, z: 4}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 27, y: 0, z: 20}
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 5}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 27, y: 0, z: 23}
      sizes: 
      - !Vector3 {x: 8, y: 8, z: 8}
