#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 15, y: 0, z: 27}
      rotations: [99]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
      colors: 
      - !RGB {r: 232, g: 225, b: 90}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 29, y: 0, z: 19}
      rotations: [334]
      sizes: 
      - !Vector3 {x: 5, y: 13, z: 3}
      colors: 
      - !RGB {r: 99, g: 186, b: 211}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 27, y: 0, z: 25}
      rotations: [23]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 34, y: 0, z: 25}
      rotations: [275]
      sizes: 
      - !Vector3 {x: 4, y: 6, z: 5}
      colors: 
      - !RGB {r: 198, g: 228, b: 175}
