#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 5, y: 0, z: 18}
      rotations: [112]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 14}
      colors: 
      - !RGB {r: 37, g: 165, b: 225}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 31, y: 0, z: 28}
      rotations: [148]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 5}
      colors: 
      - !RGB {r: 206, g: 21, b: 91}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 15, y: 0, z: 29}
      rotations: [217]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 14}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 5, y: 0, z: 28}
      rotations: [9]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 14}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 5, y: 0, z: 22}
      rotations: [232]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
