#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 6, y: 0, z: 26}
      rotations: [61]
      sizes: 
      - !Vector3 {x: 4, y: 6, z: 5}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 20, y: 0, z: 27}
      rotations: [5]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 29, y: 0, z: 25}
      rotations: [74]
      sizes: 
      - !Vector3 {x: 13, y: 5, z: 7}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 32, y: 0, z: 20}
      rotations: [117]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
