#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 7, y: 0, z: 25}
      rotations: [94]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
      colors: 
      - !RGB {r: 253, g: 56, b: 29}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 17, y: 0, z: 21}
      rotations: [176]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 2}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 14, y: 0, z: 17}
      rotations: [73]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 8}
      colors: 
      - !RGB {r: 11, g: 3, b: 111}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 6, y: 0, z: 26}
      rotations: [151]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 8}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 28, y: 0, z: 28}
      rotations: [4]
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 10}
