#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 13, y: 0, z: 22}
      rotations: [102]
      sizes: 
      - !Vector3 {x: 5, y: 10, z: 1}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 18, y: 0, z: 23}
      rotations: [218]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
      colors: 
      - !RGB {r: 236, g: 234, b: 13}
