#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 29, y: 0, z: 29}
      rotations: [37]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 6}
      colors: 
      - !RGB {r: 51, g: 101, b: 235}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 5, y: 0, z: 18}
      rotations: [243]
      sizes: 
      - !Vector3 {x: 5, y: 8, z: 3}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 22, y: 0, z: 22}
      rotations: [120]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 6}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 8, y: 0, z: 17}
      rotations: [302]
      sizes: 
      - !Vector3 {x: 4, y: 3, z: 7}
      colors: 
      - !RGB {r: 126, g: 251, b: 170}
