#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 6, y: 0, z: 22}
      rotations: [13]
      sizes: 
      - !Vector3 {x: 5, y: 11, z: 4}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 13, y: 0, z: 17}
      rotations: [88]
      sizes: 
      - !Vector3 {x: 9, y: 4, z: 8}
      colors: 
      - !RGB {r: 244, g: 61, b: 227}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 20, y: 0, z: 27}
      rotations: [136]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
      colors: 
      - !RGB {r: 20, g: 25, b: 148}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 20, y: 0, z: 18}
      rotations: [339]
      sizes: 
      - !Vector3 {x: 3, y: 14, z: 3}
      colors: 
      - !RGB {r: 179, g: 70, b: 152}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 21, y: 0, z: 21}
      rotations: [335]
      sizes: 
      - !Vector3 {x: 2, y: 4, z: 14}
