#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 27, y: 0, z: 25}
      rotations: [289]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 5}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 23, y: 0, z: 30}
      rotations: [276]
      sizes: 
      - !Vector3 {x: 2, y: 9, z: 3}
      colors: 
      - !RGB {r: 207, g: 230, b: 195}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 22, y: 0, z: 20}
      rotations: [9]
      sizes: 
      - !Vector3 {x: 12, y: 1, z: 13}
      colors: 
      - !RGB {r: 3, g: 108, b: 120}
