#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 15, y: 0, z: 30}
      rotations: [173]
      sizes: 
      - !Vector3 {x: 5, y: 11, z: 4}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 6, y: 0, z: 18}
      rotations: [244]
      sizes: 
      - !Vector3 {x: 10, y: 5, z: 5}
