#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 12, y: 0, z: 17}
      rotations: [273]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 6}
      colors: 
      - !RGB {r: 34, g: 206, b: 116}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 7, y: 0, z: 27}
      rotations: [199]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 5}
      colors: 
      - !RGB {r: 182, g: 174, b: 168}
