#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 30, y: 0, z: 23}
      rotations: [63]
      sizes: 
      - !Vector3 {x: 8, y: 1, z: 11}
      colors: 
      - !RGB {r: 163, g: 117, b: 149}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 30, y: 0, z: 25}
      rotations: [191]
      sizes: 
      - !Vector3 {x: 5, y: 13, z: 3}
      colors: 
      - !RGB {r: 223, g: 171, b: 38}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 25, y: 0, z: 18}
      rotations: [47]
      sizes: 
      - !Vector3 {x: 3, y: 4, z: 8}
      colors: 
      - !RGB {r: 249, g: 233, b: 11}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 26, y: 0, z: 23}
      rotations: [294]
      sizes: 
      - !Vector3 {x: 2, y: 8, z: 2}
      colors: 
      - !RGB {r: 226, g: 134, b: 199}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 5, y: 0, z: 21}
      rotations: [22]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
      colors: 
      - !RGB {r: 39, g: 20, b: 68}
