#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 11, y: 0, z: 27}
      rotations: [29]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 13}
      colors: 
      - !RGB {r: 221, g: 231, b: 104}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 24, y: 0, z: 18}
      rotations: [329]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 53, g: 240, b: 32}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 20, y: 0, z: 19}
      rotations: [39]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
