#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 13, y: 0, z: 27}
      rotations: [178]
      sizes: 
      - !Vector3 {x: 8, y: 5, z: 8}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 11, y: 0, z: 25}
      rotations: [277]
      sizes: 
      - !Vector3 {x: 2, y: 4, z: 14}
      colors: 
      - !RGB {r: 83, g: 115, b: 183}
