#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 28, y: 0, z: 22}
      rotations: [225]
      sizes: 
      - !Vector3 {x: 4, y: 6, z: 5}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 14, y: 0, z: 19}
      rotations: [330]
      sizes: 
      - !Vector3 {x: 4, y: 4, z: 7}
      colors: 
      - !RGB {r: 254, g: 147, b: 88}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 12, y: 0, z: 30}
      rotations: [172]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 14}
      colors: 
      - !RGB {r: 140, g: 147, b: 67}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 12, y: 0, z: 29}
      rotations: [216]
      sizes: 
      - !Vector3 {x: 6, y: 4, z: 6}
      colors: 
      - !RGB {r: 210, g: 146, b: 116}
