#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 15, y: 0, z: 25}
      rotations: [171]
      sizes: 
      - !Vector3 {x: 6, y: 4, z: 6}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 32, y: 0, z: 28}
      rotations: [342]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 14}
      colors: 
      - !RGB {r: 99, g: 127, b: 44}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 34, y: 0, z: 24}
      rotations: [349]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 125, g: 178, b: 150}
