#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 13, y: 0, z: 21}
      sizes: 
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 15, y: 0, z: 17}
      sizes: 
      - !Vector3 {x: 10, y: 10, z: 10}
