#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 22, y: 0, z: 19}
      rotations: [134]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 10}
      colors: 
      - !RGB {r: 112, g: 5, b: 162}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 15, y: 0, z: 17}
      rotations: [23]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 6, y: 0, z: 25}
      rotations: [253]
      sizes: 
      - !Vector3 {x: 5, y: 8, z: 3}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 34, y: 0, z: 27}
      rotations: [77]
      sizes: 
      - !Vector3 {x: 2, y: 8, z: 2}
      colors: 
      - !RGB {r: 111, g: 36, b: 161}
