#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 31, y: 0, z: 24}
      rotations: [67]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 14}
      colors: 
      - !RGB {r: 56, g: 94, b: 203}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 7, y: 0, z: 17}
      rotations: [88]
      sizes: 
      - !Vector3 {x: 1, y: 2, z: 8}
      colors: 
      - !RGB {r: 18, g: 235, b: 119}
