#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 13, y: 0, z: 28}
      rotations: [198]
      sizes: 
      - !Vector3 {x: 1, y: 2, z: 8}
      colors: 
      - !RGB {r: 31, g: 203, b: 90}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 33, y: 0, z: 20}
      rotations: [279]
      sizes: 
      - !Vector3 {x: 4, y: 2, z: 5}
      colors: 
      - !RGB {r: 55, g: 209, b: 50}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 35, y: 0, z: 20}
      rotations: [333]
      sizes: 
      - !Vector3 {x: 4, y: 3, z: 7}
      colors: 
      - !RGB {r: 147, g: 209, b: 236}
