#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 19, y: 0, z: 20}
      rotations: [278]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 2}
      colors: 
      - !RGB {r: 198, g: 53, b: 253}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 33, y: 0, z: 27}
      rotations: [218]
      sizes: 
      - !Vector3 {x: 10, y: 5, z: 5}
      colors: 
      - !RGB {r: 217, g: 140, b: 59}
