#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 16, y: 0, z: 26}
      rotations: [217]
      sizes: 
      - !Vector3 {x: 1, y: 15, z: 5}
      colors: 
      - !RGB {r: 9, g: 58, b: 80}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 6, y: 0, z: 25}
      rotations: [72]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 11}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 21, y: 0, z: 21}
      rotations: [214]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
      colors: 
      - !RGB {r: 206, g: 94, b: 30}
