#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 26, y: 0, z: 27}
      rotations: [162]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 5}
      colors: 
      - !RGB {r: 132, g: 219, b: 52}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 12, y: 0, z: 21}
      rotations: [282]
      sizes: 
      - !Vector3 {x: 3, y: 14, z: 3}
      colors: 
      - !RGB {r: 37, g: 200, b: 234}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 24, y: 0, z: 21}
      rotations: [84]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 8}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 12, y: 0, z: 19}
      rotations: [332]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 1}
      colors: 
      - !RGB {r: 185, g: 202, b: 195}
