#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 5, y: 0, z: 24}
      rotations: [346]
      sizes: 
      - !Vector3 {x: 12, y: 1, z: 13}
      colors: 
      - !RGB {r: 243, g: 188, b: 25}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 6, y: 0, z: 24}
      rotations: [138]
      sizes: 
      - !Vector3 {x: 5, y: 8, z: 3}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 27, y: 0, z: 24}
      rotations: [220]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 14}
      colors: 
      - !RGB {r: 34, g: 58, b: 142}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 33, y: 0, z: 17}
      rotations: [327]
      sizes: 
      - !Vector3 {x: 1, y: 2, z: 8}
      colors: 
      - !RGB {r: 124, g: 60, b: 51}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 34, y: 0, z: 18}
      rotations: [123]
      sizes: 
      - !Vector3 {x: 5, y: 10, z: 1}
      colors: 
      - !RGB {r: 246, g: 163, b: 116}
