#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 25, y: 0, z: 26}
      rotations: [279]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 29, y: 0, z: 28}
      rotations: [119]
      sizes: 
      - !Vector3 {x: 5, y: 10, z: 1}
      colors: 
      - !RGB {r: 130, g: 189, b: 235}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 11, y: 0, z: 24}
      rotations: [273]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
      colors: 
      - !RGB {r: 143, g: 214, b: 29}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 8, y: 0, z: 19}
      rotations: [272]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
      colors: 
      - !RGB {r: 104, g: 202, b: 74}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 30, y: 0, z: 20}
      rotations: [84]
      sizes: 
      - !Vector3 {x: 5, y: 13, z: 3}
      colors: 
      - !RGB {r: 174, g: 122, b: 77}
