#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 16, y: 0, z: 21}
      rotations: [209]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 4, g: 169, b: 249}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 23, y: 0, z: 21}
      rotations: [161]
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 10}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 35, y: 0, z: 22}
      rotations: [245]
      sizes: 
      - !Vector3 {x: 2, y: 8, z: 2}
      colors: 
      - !RGB {r: 130, g: 63, b: 27}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 26, y: 0, z: 23}
      rotations: [306]
      sizes: 
      - !Vector3 {x: 3, y: 4, z: 8}
      colors: 
      - !RGB {r: 235, g: 206, b: 10}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 12, y: 0, z: 28}
      rotations: [283]
      sizes: 
      - !Vector3 {x: 6, y: 1, z: 13}
      colors: 
      - !RGB {r: 0, g: 217, b: 77}
