#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 21, y: 0, z: 21}
      rotations: [201]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
      colors: 
      - !RGB {r: 102, g: 61, b: 91}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 18, y: 0, z: 24}
      rotations: [23]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 19, y: 0, z: 22}
      rotations: [283]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 5}
      colors: 
      - !RGB {r: 108, g: 242, b: 99}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 8, y: 0, z: 24}
      rotations: [181]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
      colors: 
      - !RGB {r: 71, g: 166, b: 15}
