#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 21, y: 0, z: 22}
      rotations: [9]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 11}
      colors: 
      - !RGB {r: 119, g: 182, b: 139}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 16, y: 0, z: 29}
      rotations: [199]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
      colors: 
      - !RGB {r: 18, g: 99, b: 32}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 35, y: 0, z: 21}
      rotations: [326]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 14}
      colors: 
      - !RGB {r: 20, g: 197, b: 205}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 21, y: 0, z: 19}
      rotations: [74]
      sizes: 
      - !Vector3 {x: 5, y: 11, z: 4}
