#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 14, y: 0, z: 24}
      rotations: [206]
      sizes: 
      - !Vector3 {x: 5, y: 11, z: 4}
      colors: 
      - !RGB {r: 199, g: 118, b: 90}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 32, y: 0, z: 21}
      rotations: [49]
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 10}
      colors: 
      - !RGB {r: 194, g: 112, b: 27}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 25, y: 0, z: 19}
      rotations: [76]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 10}
      colors: 
      - !RGB {r: 236, g: 255, b: 11}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 11, y: 0, z: 20}
      rotations: [138]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 15}
      colors: 
      - !RGB {r: 240, g: 152, b: 83}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 35, y: 0, z: 20}
      rotations: [339]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 8}
      colors: 
      - !RGB {r: 94, g: 191, b: 66}
