#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 8, y: 0, z: 19}
      rotations: [70]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 1}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 24, y: 0, z: 24}
      rotations: [28]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
      colors: 
      - !RGB {r: 26, g: 148, b: 73}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 29, y: 0, z: 28}
      rotations: [273]
      sizes: 
      - !Vector3 {x: 2, y: 5, z: 3}
      colors: 
      - !RGB {r: 208, g: 131, b: 85}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 16, y: 0, z: 21}
      rotations: [128]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 47, g: 165, b: 2}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 32, y: 0, z: 18}
      rotations: [175]
      sizes: 
      - !Vector3 {x: 9, y: 4, z: 8}
      colors: 
      - !RGB {r: 228, g: 146, b: 239}
