#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 5, y: 0, z: 24}
      rotations: [1]
      sizes: 
      - !Vector3 {x: 8, y: 1, z: 11}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 30, y: 0, z: 27}
      rotations: [210]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 156, g: 226, b: 167}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 22, y: 0, z: 30}
      rotations: [6]
      sizes: 
      - !Vector3 {x: 4, y: 4, z: 7}
      colors: 
      - !RGB {r: 6, g: 221, b: 34}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 32, y: 0, z: 25}
      rotations: [113]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
      colors: 
      - !RGB {r: 15, g: 248, b: 50}
