#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 17, y: 0, z: 26}
      rotations: [112]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
      colors: 
      - !RGB {r: 240, g: 63, b: 162}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 6, y: 0, z: 27}
      rotations: [308]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 14}
      colors: 
      - !RGB {r: 145, g: 16, b: 252}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 15, y: 0, z: 21}
      rotations: [178]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
      colors: 
      - !RGB {r: 153, g: 84, b: 56}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 27, y: 0, z: 24}
      rotations: [93]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 15}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 15, y: 0, z: 23}
      rotations: [259]
      sizes: 
      - !Vector3 {x: 1, y: 12, z: 3}
