#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 17, y: 0, z: 17}
      rotations: [235]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
      colors: 
      - !RGB {r: 108, g: 134, b: 224}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 28, y: 0, z: 23}
      rotations: [42]
      sizes: 
      - !Vector3 {x: 3, y: 14, z: 3}
      colors: 
      - !RGB {r: 233, g: 138, b: 253}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 33, y: 0, z: 29}
      rotations: [59]
      sizes: 
      - !Vector3 {x: 9, y: 4, z: 8}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 26, y: 0, z: 30}
      rotations: [155]
      sizes: 
      - !Vector3 {x: 1, y: 15, z: 5}
      colors: 
      - !RGB {r: 64, g: 29, b: 54}
