#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 32, y: 0, z: 18}
      rotations: [292]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 23, y: 0, z: 21}
      rotations: [241]
      sizes: 
      - !Vector3 {x: 13, y: 5, z: 7}
      colors: 
      - !RGB {r: 250, g: 29, b: 1}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 15, y: 0, z: 27}
      rotations: [117]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 1}
      colors: 
      - !RGB {r: 15, g: 166, b: 168}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 20, y: 0, z: 30}
      rotations: [5]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 209, g: 32, b: 205}
