#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 27, y: 0, z: 17}
      rotations: [302]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 12, y: 0, z: 20}
      rotations: [216]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
      colors: 
      - !RGB {r: 37, g: 221, b: 132}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 14, y: 0, z: 17}
      rotations: [185]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 5}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 33, y: 0, z: 17}
      rotations: [171]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
