#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 20, y: 0, z: 27}
      rotations: [81]
      sizes: 
      - !Vector3 {x: 4, y: 2, z: 5}
      colors: 
      - !RGB {r: 110, g: 249, b: 159}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 23, y: 0, z: 17}
      rotations: [218]
      sizes: 
      - !Vector3 {x: 11, y: 2, z: 10}
      colors: 
      - !RGB {r: 211, g: 225, b: 135}
