#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 6, y: 0, z: 17}
      rotations: [9]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 23, y: 0, z: 23}
      rotations: [349]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 14}
      colors: 
      - !RGB {r: 85, g: 207, b: 180}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 18, y: 0, z: 24}
      rotations: [223]
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 10}
      colors: 
      - !RGB {r: 92, g: 37, b: 204}
