#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 19, y: 0, z: 18}
      rotations: [97]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 5}
      colors: 
      - !RGB {r: 22, g: 84, b: 254}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 7, y: 0, z: 25}
      rotations: [194]
      sizes: 
      - !Vector3 {x: 5, y: 3, z: 15}
      colors: 
      - !RGB {r: 124, g: 51, b: 105}
