#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 5, y: 0, z: 19}
      sizes: 
      - !Vector3 {x: 9, y: 9, z: 9}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 35, y: 0, z: 21}
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 5}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 31, y: 0, z: 24}
      sizes: 
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 24, y: 0, z: 18}
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 3}
