#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 21, y: 0, z: 23}
      rotations: [45]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 26, y: 0, z: 28}
      rotations: [111]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
      colors: 
      - !RGB {r: 90, g: 66, b: 199}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 32, y: 0, z: 28}
      rotations: [32]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 58, g: 247, b: 12}
