#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 26, y: 0, z: 21}
      rotations: [302]
      sizes: 
      - !Vector3 {x: 2, y: 13, z: 5}
      colors: 
      - !RGB {r: 214, g: 209, b: 29}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 19, y: 0, z: 18}
      rotations: [303]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
      colors: 
      - !RGB {r: 146, g: 180, b: 142}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 34, y: 0, z: 24}
      rotations: [36]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
