#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 17, y: 0, z: 23}
      rotations: [283]
      sizes: 
      - !Vector3 {x: 10, y: 1, z: 6}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 15, y: 0, z: 28}
      rotations: [264]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 6}
      colors: 
      - !RGB {r: 219, g: 60, b: 122}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 24, y: 0, z: 21}
      rotations: [179]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 1}
      colors: 
      - !RGB {r: 218, g: 236, b: 171}
    - !Item
      name: LObject
      positions: 
      - !Vector3 {x: 10, y: 0, z: 29}
      rotations: [265]
      sizes: 
      - !Vector3 {x: 12, y: 1, z: 13}
      colors: 
      - !RGB {r: 205, g: 237, b: 79}
