#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 23, y: 0, z: 18}
      rotations: [130]
      sizes: 
      - !Vector3 {x: 4, y: 3, z: 7}
      colors: 
      - !RGB {r: 2, g: 120, b: 234}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 26, y: 0, z: 29}
      rotations: [297]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 6}
      colors: 
      - !RGB {r: 138, g: 22, b: 229}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 21, y: 0, z: 22}
      rotations: [108]
      sizes: 
      - !Vector3 {x: 13, y: 5, z: 7}
      colors: 
      - !RGB {r: 246, g: 46, b: 204}
