#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 23, y: 0, z: 28}
      rotations: [208]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 8}
      colors: 
      - !RGB {r: 245, g: 172, b: 49}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 34, y: 0, z: 27}
      rotations: [214]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 14}
      colors: 
      - !RGB {r: 173, g: 239, b: 118}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 24, y: 0, z: 17}
      rotations: [301]
      sizes: 
      - !Vector3 {x: 5, y: 5, z: 14}
      colors: 
      - !RGB {r: 255, g: 50, b: 198}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 30, y: 0, z: 24}
      rotations: [146]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 6, y: 0, z: 24}
      rotations: [319]
      sizes: 
      - !Vector3 {x: 5, y: 13, z: 3}
      colors: 
      - !RGB {r: 76, g: 77, b: 64}
