#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 27, y: 0, z: 28}
      rotations: [283]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 10}
      colors: 
      - !RGB {r: 236, g: 191, b: 59}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 34, y: 0, z: 25}
      rotations: [149]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
      colors: 
      - !RGB {r: 199, g: 29, b: 96}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 7, y: 0, z: 25}
      rotations: [252]
      sizes: 
      - !Vector3 {x: 5, y: 4, z: 13}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 20, y: 0, z: 17}
      rotations: [10]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 10}
      colors: 
      - !RGB {r: 27, g: 248, b: 230}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 33, y: 0, z: 30}
      rotations: [234]
      sizes: 
      - !Vector3 {x: 4, y: 3, z: 7}
