#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 15, y: 0, z: 27}
      rotations: [292]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 10}
      colors: 
      - !RGB {r: 254, g: 209, b: 11}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 20, y: 0, z: 19}
      rotations: [25]
      sizes: 
      - !Vector3 {x: 3, y: 5, z: 14}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 35, y: 0, z: 18}
      rotations: [44]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 14}
      colors: 
      - !RGB {r: 39, g: 33, b: 155}
