#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 33, y: 0, z: 30}
      rotations: [27]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 18, y: 0, z: 30}
      rotations: [29]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
      colors: 
      - !RGB {r: 6, g: 97, b: 98}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 12, y: 0, z: 27}
      rotations: [304]
      sizes: 
      - !Vector3 {x: 4, y: 5, z: 2}
      colors: 
      - !RGB {r: 157, g: 253, b: 56}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 16, y: 0, z: 30}
      rotations: [207]
      sizes: 
      - !Vector3 {x: 11, y: 4, z: 7}
      colors: 
      - !RGB {r: 49, g: 243, b: 55}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 16, y: 0, z: 21}
      rotations: [31]
      sizes: 
      - !Vector3 {x: 3, y: 2, z: 10}
