#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 29, y: 0, z: 21}
      rotations: [147]
      sizes: 
      - !Vector3 {x: 9, y: 2, z: 12}
      colors: 
      - !RGB {r: 32, g: 62, b: 229}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 29, y: 0, z: 28}
      rotations: [212]
      sizes: 
      - !Vector3 {x: 1, y: 15, z: 5}
