#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 7, y: 0, z: 27}
      rotations: [52]
      sizes: 
      - !Vector3 {x: 4, y: 3, z: 7}
      colors: 
      - !RGB {r: 79, g: 241, b: 120}
    - !Item
      name: CylinderTunnel
      positions: 
      - !Vector3 {x: 14, y: 0, z: 21}
      rotations: [151]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 10}
      colors: 
      - !RGB {r: 187, g: 92, b: 71}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 13, y: 0, z: 30}
      rotations: [126]
      sizes: 
      - !Vector3 {x: 9, y: 4, z: 8}
      colors: 
      - !RGB {r: 208, g: 8, b: 28}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 11, y: 0, z: 23}
      rotations: [266]
      sizes: 
      - !Vector3 {x: 5, y: 11, z: 4}
      colors: 
      - !RGB {r: 38, g: 67, b: 215}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 20, y: 0, z: 27}
      rotations: [307]
      sizes: 
      - !Vector3 {x: 1, y: 14, z: 3}
