#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 32, y: 0, z: 27}
      rotations: [214]
      sizes: 
      - !Vector3 {x: 3, y: 3, z: 10}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 14, y: 0, z: 24}
      rotations: [289]
      sizes: 
      - !Vector3 {x: 5, y: 11, z: 4}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 32, y: 0, z: 27}
      rotations: [235]
      sizes: 
      - !Vector3 {x: 2, y: 4, z: 14}
      colors: 
      - !RGB {r: 41, g: 70, b: 110}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 30, y: 0, z: 23}
      rotations: [147]
      sizes: 
      - !Vector3 {x: 8, y: 1, z: 11}
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 24, y: 0, z: 21}
      rotations: [154]
      sizes: 
      - !Vector3 {x: 3, y: 4, z: 8}
      colors: 
      - !RGB {r: 65, g: 22, b: 114}
