#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: UObject
      positions: 
      - !Vector3 {x: 21, y: 0, z: 18}
      rotations: [265]
      sizes: 
      - !Vector3 {x: 15, y: 2, z: 6}
      colors: 
      - !RGB {r: 199, g: 116, b: 30}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 32, y: 0, z: 29}
      rotations: [128]
      sizes: 
      - !Vector3 {x: 5, y: 14, z: 3}
