#An example configure file
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.0
    t: 250
    items:
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 16, y: 0, z: 28}
      rotations: [170]
      sizes: 
      - !Vector3 {x: 3, y: 4, z: 8}
      colors: 
      - !RGB {r: 1, g: 146, b: 81}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 24, y: 0, z: 24}
      rotations: [126]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
      colors: 
      - !RGB {r: 161, g: 20, b: 25}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 29, y: 0, z: 30}
      rotations: [22]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 14}
    - !Item
      name: Cardbox1
      positions: 
      - !Vector3 {x: 14, y: 0, z: 19}
      rotations: [208]
      sizes: 
      - !Vector3 {x: 1, y: 11, z: 4}
    - !Item
      name: Cardbox2
      positions: 
      - !Vector3 {x: 28, y: 0, z: 20}
      rotations: [222]
      sizes: 
      - !Vector3 {x: 1, y: 4, z: 5}
